# This is a basic workflow to help you get started with Actions

name: update-readme

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # https://stackoverflow.com/questions/60868897/git-log-dates-incorrect-in-a-github-action
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v2
      - name: install dependencies
        run: pip install openai
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python tag.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Commit files
        #if: "! git status --short" # check if there are changes to commit
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "action@github.com"
          git add README.md
          git add tags/*
          # Thanks for the trick, ChatGPT!
          if git diff-index --quiet HEAD --; then
            echo "changes_to_push=false" >> $GITHUB_ENV
          else
            git commit -m "Updated TOC"
            echo "changes_to_push=true" >> $GITHUB_ENV
          fi
      - name: Push changes # push the output folder to your repo
        if: ${{ env.changes_to_push == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
